name 'killclient'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures killclient'
long_description 'Installs/Configures killclient'
version '0.2.1'
